app/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name='index'),
    path('speedtest/', views.speedtest_view, name='speedtest'),
    path('save/', views.save_iperf, name='iperf'),
    path('<int:pk>/', views.result_view, name='result'),
    path('<int:pk>.png', views.image_view, name='image'),
    path('<int:pk>/graph/', views.graph_view, name='graph'),
    path('<int:pk>/map/', views.map_view, name='map'),
    path('ajax/tdata/<int:pk>/', views.tdata_view_a),
    path('ajax/graph/<int:pk>/', views.graph_view_a),
    path('ajax/map/<int:pk>/', views.map_view_a),
    path('ajax/delete/hook/<int:pk>/', views.del_hook_view_a),
    # path('ajax/delete/result/<int:pk>/', views.del_result_view_a),
]

app/pyperf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    path('', include('home.urls')),
    path('oauth/', include('oauth.urls')),
    path('admin/', admin.site.urls),
    path('flower/', RedirectView.as_view(url='/flower/'), name='flower'),
    path('redis/', RedirectView.as_view(url='/redis/'), name='redis'),
    path('phpmyadmin/', RedirectView.as_view(url='/phpmyadmin/'), name='phpmyadmin'),
    path('flush-cache/', views.flush_cache_view, name='flush_cache'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler400 = 'pyperf.views.handler400_view'
# handler403 = 'pyperf.views.handler403_view'
# handler404 = 'pyperf.views.handler404_view'
# handler500 = 'pyperf.views.handler500_view'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('debug/', include(debug_toolbar.urls))] + urlpatterns

app/templates/include/table-head.html
<tr>
    <th scope="col" title="Internal ID">ID</th>
    <th scope="col" class="text-center"></th>
    <th scope="col" class="d-none d-md-table-cell text-center" title="Duration">Time</th>
    <th scope="col" title="BPS">Speed</th>
    <th scope="col" class="d-none d-sm-table-cell text-center" title="Number of Streams">#</th>
    <th scope="col">Hostname</th>
    <th scope="col" class="d-none d-md-table-cell text-center"></th>
    <th scope="col" class="d-none d-lg-table-cell">IP Address</th>
    <th scope="col" class="d-none d-xl-table-cell" title="UTC">Date</th>
    <th scope="col" class="d-none d-sm-table-cell text-center"></th>
{#    {% if request.user.is_superuser %}#}
{#        <th scope="col" title="Delete Result">Trash</th>#}
{#    {% endif %}#}
</tr>

app/templates/include/table-tr.html
{% load tz %}
{% load home_tags %}
<tr>
    <th><a href="{% url 'home:result' data.id %}">
        {{ data.id }}</a></th>
    <td class="text-center">
        {% if data.reverse %}
            <i class="fa-solid fa-cloud-arrow-down text-success" title="Download"></i>
        {% else %}
            <i class="fa-solid fa-cloud-arrow-up text-warning" title="Upload"></i>
        {% endif %}
    </td>
    <td class="d-none d-md-table-cell text-center">
        <a class="clip text-white text-decoration-none" role="button"
           data-clipboard-text="{{ data.duration }}">{{ data.duration }} s</a></td>
    <td><a class="clip text-white text-decoration-none" role="button"
           data-clipboard-text="{{ data.bps_human }}">{{ data.bps_human }}</a></td>
    <td class="d-none d-sm-table-cell text-center">
        <a class="clip text-white text-decoration-none text-center" role="button"
           data-clipboard-text="{{ data.num_streams }}">x{{ data.num_streams }}</a></td>
    <td><a class="clip text-white text-decoration-none" role="button"
           data-clipboard-text="{{ data.name }}">{{ data.name }}</a></td>
    <td class="d-none d-md-table-cell text-center">{% if data.ip_cc %}
        <a class="clip text-white text-decoration-none" role="button"
           data-clipboard-text="{{ data.ip_country|default:data.ip_cc }}">{{ data.ip_cc|cc_to_flag }}</a>{% else %}
        <i class="fa-solid fa-network-wired text-white"></i>{% endif %}</td>
    <td class="d-none d-lg-table-cell"><a class="clip text-white text-decoration-none" role="button"
           data-clipboard-text="{{ data.ip }}">{{ data.ip }}</a></td>
    <td class="d-none d-xl-table-cell"><a class="clip text-white text-decoration-none" role="button"
           data-clipboard-text="{{ data.created_at|localtime }}">{{ data.created_at|localtime }}</a></td>
    <td class="d-none d-sm-table-cell text-center">
        <a href="{% url 'home:image' data.id %}" class="text-white" target="_blank" title="Image"><i class="fa-regular fa-image"></i></a>
        <a href="{% url 'home:graph' data.id %}" class="text-white" target="_blank" title="Graph"><i class="fa-solid fa-chart-line"></i></a></td>
{#    {% if request.user.is_superuser %}#}
{#        <td><a role="button" class="delete-result-btn" data-hook-id="{{ data.id }}">#}
{#            <i class="fa-solid fa-trash-can link-danger"></i></a></td>#}
{#    {% endif %}#}
</tr>