app/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name='index'),
    path('speedtest/', views.speedtest_view, name='speedtest'),
    path('save/', views.save_iperf, name='iperf'),
    path('<int:pk>/', views.result_view, name='result'),
    path('<int:pk>.png', views.image_view, name='image'),
    path('<int:pk>/graph/', views.graph_view, name='graph'),
    path('<int:pk>/map/', views.map_view, name='map'),
    path('ajax/tdata/<int:pk>/', views.tdata_view_a),
    path('ajax/graph/<int:pk>/', views.graph_view_a),
    path('ajax/map/<int:pk>/', views.map_view_a),
    path('ajax/delete/hook/<int:pk>/', views.del_hook_view_a),
    # path('ajax/delete/result/<int:pk>/', views.del_result_view_a),
]

app/oauth/urls.py
from django.urls import path
from . import views

app_name = 'oauth'

urlpatterns = [
    path('', views.oauth_start, name='login'),
    path('logout/', views.oauth_logout, name='logout'),
    path('callback/', views.oauth_callback, name='callback'),
    path('webhook/', views.oauth_webhook, name='webhook'),
]

app/pyperf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    path('', include('home.urls')),
    path('oauth/', include('oauth.urls')),
    path('admin/', admin.site.urls),
    path('flower/', RedirectView.as_view(url='/flower/'), name='flower'),
    path('redis/', RedirectView.as_view(url='/redis/'), name='redis'),
    path('phpmyadmin/', RedirectView.as_view(url='/phpmyadmin/'), name='phpmyadmin'),
    path('flush-cache/', views.flush_cache_view, name='flush_cache'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# handler400 = 'pyperf.views.handler400_view'
# handler403 = 'pyperf.views.handler403_view'
# handler404 = 'pyperf.views.handler404_view'
# handler500 = 'pyperf.views.handler500_view'


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('debug/', include(debug_toolbar.urls))] + urlpatterns

app/home/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from oauth.models import CustomUser


class SpeedTest(models.Model):
    PROTOCOL_CHOICES = [
        ('TCP', 'TCP'),
        ('UDP', 'UDP'),
    ]
    id = models.AutoField(primary_key=True)
    ip = models.CharField(blank=True, max_length=15, verbose_name='IP Address')
    name = models.CharField(blank=True, max_length=128, verbose_name='Host name')
    reverse = models.BooleanField(null=True, verbose_name='Reverse (Download)')
    bps = models.FloatField(null=True, verbose_name='BPS')
    bps_human = models.CharField(blank=True, max_length=32, verbose_name='BPS Human')
    bytes = models.IntegerField(null=True, verbose_name='Bytes')
    bytes_human = models.CharField(blank=True, max_length=32, verbose_name='Bytes Human')
    duration = models.IntegerField(null=True, verbose_name='Duration')
    num_streams = models.IntegerField(null=True, verbose_name='Streams', default=1)
    protocol = models.CharField(
        blank=True,
        max_length=3,
        choices=PROTOCOL_CHOICES,
        verbose_name='Protocol',
    )
    jitter = models.FloatField(null=True, verbose_name='Jitter')
    ip_cc = models.CharField(blank=True, max_length=2, verbose_name='IP Country Code')
    ip_country = models.CharField(blank=True, max_length=32, verbose_name='IP Country Name')
    ip_rc = models.CharField(blank=True, max_length=32, verbose_name='IP Region Code')
    ip_region = models.CharField(blank=True, max_length=32, verbose_name='IP Region Name')
    ip_city = models.CharField(blank=True, max_length=32, verbose_name='IP City')
    ip_org = models.CharField(blank=True, max_length=32, verbose_name='IP Organization')
    ip_lat = models.FloatField(null=True, verbose_name='IP Latitude')
    ip_lon = models.FloatField(null=True, verbose_name='IP Longitude')
    packets = models.IntegerField(null=True, verbose_name='Packets Total')
    lost = models.IntegerField(null=True, verbose_name='Packets Lost')
    json = models.JSONField()
    version = models.CharField(blank=True, max_length=32, verbose_name='Iperf3 Version')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}: {} ({})'.format(self.pk, self.name, self.bps_human)

    class Meta:
        verbose_name = 'Speed Test'
        verbose_name_plural = 'Speed Tests'
        get_latest_by = 'pk'

    def get_type(self):
        return 'Download' if self.reverse else 'Upload'

    def get_result_url(self):
        url = reverse('home:result', kwargs={'pk': self.pk})
        return f'{settings.SITE_URL}{url}'

    def get_image_url(self):
        url = reverse('home:image', kwargs={'pk': self.pk})
        return f'{settings.SITE_URL}{url}'

    def get_graph_url(self):
        url = reverse('home:graph', kwargs={'pk': self.pk})
        return f'{settings.SITE_URL}{url}'

    def get_map_url(self):
        url = reverse('home:map', kwargs={'pk': self.pk})
        return f'{settings.SITE_URL}{url}'


class Webhooks(models.Model):
    id = models.AutoField(primary_key=True)
    url = models.URLField(unique=True, verbose_name='Webhook URL')
    hook_id = models.CharField(max_length=32, blank=True, null=True)
    guild_id = models.CharField(max_length=32, blank=True, null=True)
    channel_id = models.CharField(max_length=32, blank=True, null=True)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return '{}: {} ({})'.format(self.id, self.hook_id, self.owner.first_name)

    class Meta:
        verbose_name = 'Webhook'
        verbose_name_plural = 'Webhooks'

app/home/forms.py
from django import forms

app/home/views.py
import json
import logging
import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.views.decorators.vary import vary_on_headers
from .models import SpeedTest, Webhooks
from .tasks import process_data

logger = logging.getLogger('app')


def home_view(request):
    # View: /
    logger.debug('home_view')
    q = SpeedTest.objects.all()
    context = {'data': q}
    if request.user.is_authenticated:
        webhooks = Webhooks.objects.filter(owner=request.user)
        context.update({'webhooks': webhooks})
    return render(request, 'home.html', context)


def speedtest_view(request):
    # View: /speedtest/
    logger.debug('speedtest_view')
    return render(request, 'speedtest.html')


def result_view(request, pk):
    # View: /{pk}/
    logger.debug('result_view: %s', pk)
    q = get_object_or_404(SpeedTest, pk=pk)
    return render(request, 'result.html', {'data': q})


@cache_page(60 * 60 * 24)
def image_view(request, pk):
    # View: /{pk}.png
    logger.debug('image_view: %s', pk)
    q = get_object_or_404(SpeedTest, pk=pk)

    data = json.loads(q.json)
    if 'intervals' not in data or not data['intervals']:
        logger.debug('intervals not in query')
        raise Http404

    x = []
    for d in data['intervals']:
        x.append(d['sum']['bits_per_second'])

    pio.templates.default = 'plotly_dark'
    fig = go.Figure(go.Indicator(
        mode='gauge+number',
        value=q.bps,
        # domain={'x': [0, 1], 'y': [0, 1]},
        title={'text': f'{q.get_type()} Speed', 'font': {'size': 36}},
        gauge={'axis': {'range': [None, max(x) * 1.1]},
               'steps': [
                   {'range': [min(x), max(x)], 'color': 'gray'},
               ]}
    ))
    if not fig:
        logger.debug('no fig')
        raise Http404

    fig.update_layout(
        annotations=[
            dict(x=0, y=0.07, text=q.ip_city,
                 showarrow=False, xref='paper', yref='paper',
                 font=dict(family='sans serif', size=22, color='white')),
            dict(x=0, y=0, text=q.name,
                 showarrow=False, xref='paper', yref='paper',
                 font=dict(family='sans serif', size=22, color='white')),
            dict(x=1, y=0.07, text=q.ip_org,
                 showarrow=False, xref='paper', yref='paper',
                 font=dict(family='sans serif', size=22, color='white')),
            dict(x=1, y=0, text=q.ip,
                 showarrow=False, xref='paper', yref='paper',
                 font=dict(family='sans serif', size=22, color='white')),
        ],
        margin=dict(t=10, l=50, b=10, r=50),
    )
    return HttpResponse(fig.to_image(), content_type='image/x-png')


def graph_view(request, pk):
    # View: /{pk}/graph/
    logger.debug('graph_view: %s', pk)
    q = get_object_or_404(SpeedTest, pk=pk)
    pio.templates.default = 'plotly_dark'
    fig = render_graph_fig(q)
    if not fig:
        logger.debug('no fig')
        raise Http404

    fig.layout.title.text = f'{q.get_type()} Speed'
    return HttpResponse(fig.to_html(include_plotlyjs='cdn',
                                    config={'displaylogo': False}))


def map_view(request, pk):
    # View: /{pk}/map/
    logger.debug('map_view: %s', pk)
    q = get_object_or_404(SpeedTest, pk=pk)
    pio.templates.default = 'plotly_dark'
    fig = render_map_fig(q)
    if not fig:
        logger.debug('no fig')
        raise Http404

    return HttpResponse(fig.to_html(include_plotlyjs='cdn',
                                    config={'displaylogo': False}))


@csrf_exempt
@require_http_methods(['POST'])
def save_iperf(request):
    # View: /save/
    logger.debug('save_iperf')
    data = json.loads(request.body.decode('utf-8'))
    q = SpeedTest.objects.create(json=data)
    logger.debug(f'pk: {q.pk}')
    process_data.delay(q.pk)
    return HttpResponse(status=204)


@login_required
@csrf_exempt
@require_http_methods(['POST'])
def del_hook_view_a(request, pk):
    logger.debug('del_hook_view_a: %s', pk)
    webhook = Webhooks.objects.get(pk=pk)
    if webhook.owner != request.user:
        return HttpResponse(status=401)
    logger.debug(webhook)
    webhook.delete()
    return HttpResponse(status=204)


# @user_passes_test(lambda u: u.is_superuser)
# @csrf_exempt
# @require_http_methods(['POST'])
# def del_result_view_a(request, pk):
#     logger.debug('del_result_view_a: %s', pk)
#     speedtest = SpeedTest.objects.filter(pk=pk)
#     if speedtest:
#         speedtest[0].delete()
#     return HttpResponse(status=204)


@csrf_exempt
# @cache_page(60 * 60 * 24)
def tdata_view_a(request, pk):
    # View: /ajax/{pk}/tdata/
    logger.debug('tr_view: %s', pk)
    q = get_object_or_404(SpeedTest, pk=pk)
    response = render_to_string('include/table-tr.html', {'data': q})
    return HttpResponse(response)


@csrf_exempt
@cache_page(60 * 60 * 24)
def graph_view_a(request, pk):
    # View: /ajax/{pk}/graph/
    logger.debug('graph_view_a: %s', pk)
    q = get_object_or_404(SpeedTest, pk=pk)
    fig = render_graph_fig(q)
    if not fig:
        return HttpResponse(status=200)

    fig.update_layout(margin=dict(t=10, l=16, b=10, r=10))
    return HttpResponse(fig.to_html(include_plotlyjs=False,
                                    full_html=False,
                                    config={'displaylogo': False},))


@csrf_exempt
@cache_page(60 * 60 * 24)
def map_view_a(request, pk):
    # View: /ajax/{pk}/map/
    logger.debug('map_view_a: %s', pk)
    q = get_object_or_404(SpeedTest, pk=pk)
    fig = render_map_fig(q)
    if not fig:
        return HttpResponse(status=200)

    fig.update_layout(margin=dict(t=10, l=10, b=10, r=10))
    return HttpResponse(fig.to_html(include_plotlyjs=False,
                                    full_html=False,
                                    config={'displaylogo': False, 'scrollZoom': False},))


def render_graph_fig(query_or_pk):
    logger.debug('render_graph_fig')
    if not isinstance(query_or_pk, SpeedTest):
        query_or_pk = SpeedTest.objects.get(pk=int(query_or_pk))
    q = query_or_pk
    data = json.loads(q.json)
    if 'intervals' not in data or not data['intervals']:
        logger.debug('intervals not in query')
        return None

    x, y = [], []
    for i, d in enumerate(data['intervals']):
        x.append(i)
        y.append(d['sum']['bits_per_second'])
    df = {'Seconds': x, 'Speed': y}
    pio.templates.default = 'plotly_dark'
    fig = px.line(df, x='Seconds', y='Speed', markers=True, line_shape='linear')
    return fig


def render_map_fig(query_or_pk):
    logger.debug('render_map_fig')
    if not isinstance(query_or_pk, SpeedTest):
        query_or_pk = SpeedTest.objects.get(pk=int(query_or_pk))
    q = query_or_pk
    if not q.ip_lat or not q.ip_lon:
        return None

    pio.templates.default = 'plotly_dark'
    fig = go.Figure(go.Scattermapbox(
        lat=[str(q.ip_lat)],
        lon=[str(q.ip_lon)],
        mode='markers',
        marker=go.scattermapbox.Marker(size=14),
        text=[q.ip_city or 'Unknown'],
    ))
    fig.update_layout(
        hovermode='closest',
        mapbox=dict(
            accesstoken=settings.MAPBOX_TOKEN,
            bearing=0,
            center=go.layout.mapbox.Center(
                lat=int(q.ip_lat),
                lon=int(q.ip_lon),
            ),
            pitch=0,
            zoom=5,
        ),
    )
    return fig

app/templates/main.html
{% load static %}
{% load home_tags %}
{% load cache %}

<!doctype html>
<html lang="en" class="h-100">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% get_config 'DEBUG' as debug_enabled %}{% if debug_enabled %}
        <meta name="robots" content="noindex, nofollow">{% endif %}

    <title>PyPerf3 - {% block title %}{% endblock %}</title>

    {% block meta %}
        <meta name="author" content="Shane"/>
        <meta name="title" content="Django Iperf3"/>
        <meta name="description" content="Django Iperf3 - A Django Iperf3 Site."/>
        <meta name="theme-color" content="#2a9fd6">

        <meta property="og:author" content="Shane">
        <meta property="og:title" content="Django Iperf3">
        <meta property="og:description" content="Django Iperf3 - A Django Iperf3 Site.">
        <meta property="og:type" content="website">
        <meta property="og:url" content="{{ request.build_absolute_uri }}">
        <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{% static 'images/logo.png' %}">
    {% endblock %}

    <link rel="icon" href="{% static 'images/favicon.ico' %}" sizes="any">
    <link rel="icon" href="{% static 'images/favicon.svg' %}" type="image/svg+xml">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">

    {% block head %}{% endblock %}

</head>
<body class="d-flex flex-column h-100">

{% block navbar %}
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home:index' %}">
                <img src="{% static 'images/logo.png' %}" alt="L" width="30" height="30"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                    <li class="nav-item"><a class="nav-link {% block home_active %}{% endblock %}" href="{% url 'home:index' %}">
                        Home</a></li>
{#                    <li class="nav-item"><a class="nav-link {% block test_active %}{% endblock %}" href="{% url 'home:speedtest_view' %}">#}
{#                        Speedtest</a></li>#}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if not request.user.is_authenticated %}
                        <a href="{% url 'oauth:login' %}?next={{ request.path }}" class="btn btn-outline-primary" role="button">
                            Log in with Discord <i class="fas fa-sign-in-alt ms-2"></i></a>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}
                                <i class="fas fa-angle-down mx-1"></i>
                                <img src="{{ user|avatar_url }}"
                                     class="rounded-circle mx-2 d-none d-sm-inline d-md-inline d-lg-inline d-xl-inline" height="26" width="26" alt="P"></a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown2">
                                <li><a class="dropdown-item" role="button" data-bs-toggle="modal" data-bs-target="#user-info-modal">
                                    <i class="fas fa-user-circle me-2"></i> Profile</a></li>
                                {% if request.user.is_staff or request.user.is_superuser %}
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item text-success" href="{% url 'admin:index' %}">
                                        <i class="fa-solid fa-rocket me-2"></i> Admin</a></li>
                                {% endif %}
                                {% if request.user.is_superuser %}
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item text-warning" href="{% url 'flower' %}" target="_blank">
                                        <i class="fas fa-seedling me-2"></i> Flower <i class="fas fa-external-link-alt ms-1"></i></a></li>
                                    <li><a class="dropdown-item text-warning" href="{% url 'redis' %}" target="_blank">
                                        <i class="fa-solid fa-database me-2"></i> Redis <i class="fa-solid fa-arrow-up-right-from-square ms-1"></i></a></li>
                                    <li><a class="dropdown-item text-warning" href="{% url 'phpmyadmin' %}" target="_blank">
                                        <i class="fa-solid fa-server me-2"></i> MySQL <i class="fa-solid fa-arrow-up-right-from-square ms-1"></i></a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item text-danger" role="button" target="_blank" id="flush-cache">
                                        <i class="fa-solid fa-toilet me-2"></i> Flush Cache</a></li>
                                {% endif %}
                                <div class="dropdown-divider"></div>
                                <li><a class="dropdown-item log-out text-warning" role="button">
                                    <i class="fas fa-sign-out-alt me-2"></i> Log Out</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
{% endblock %}

<main class="flex-shrink-0">
    <div class="container-fluid p-3">

        {% block body %}{% endblock %}

    </div>
</main>

{% block backtotop %}
<button type="button" class="btn btn-primary btn-floating" id="btn-back-to-top">
    <i class="fas fa-arrow-up"></i>
</button>
{% endblock %}

{% block footer %}
<footer class="footer mt-auto">
    <div class="container-fluid p-3">
        <div class="row">
            <div class="col-12 col-md-6">
                <p class="mb-0">Join our <i class="fab fa-discord"></i>
                    <a href="{% get_config 'DISCORD_INVITE' %}" target="_blank">
                        Discord</a></p>
            </div>
            <div class="col-12 col-md-6 text-md-end">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item"><a href="{% url 'home:index' %}">
                        Home</a></li>
{#                    <li class="list-inline-item">|</li>#}
{#                    <li class="list-inline-item"><a href="{% url 'home:speedtest_view' %}">#}
{#                        Speedtest</a></li>#}
                </ul>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

{% if request.user.is_authenticated %}
    <form id="log-out" action="{% url 'oauth:logout' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.get_full_path }}">
    </form>
    <div class="modal fade" id="user-info-modal" tabindex="-1" aria-labelledby="user-info-modal-label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="user-info-modal-label">
                        <i class="fas fa-user-circle me-2"></i> Profile</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <img src="{{ user|avatar_url }}" alt="Profile Picture"
                         class="rounded float-end m-2" style="max-height:128px;max-width:128px;">
                    <h4 class="modal-title">{% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}</h4>
                    <p>Information provided by Discord.</p>
                    <p></p>
                    <div class="clearfix"></div>
                    <table class="table mt-2">
                        <tbody>
                        <tr>
                            <th>Discord ID</th>
                            <td>{{ user.username }}</td>
                        </tr>
                        <tr>
                            <th>Discord Username</th>
                            <td>{{ user.first_name }}#{{ user.last_name }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <a href="https://discord.com/login" class="btn btn-primary me-auto" role="button" target="_blank">
                        Open in Discord <i class="fas fa-external-link-alt ms-1"></i></a>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<div class="toast-container position-fixed top-0 end-0 p-3" style="margin-top: 50px;">
    {% block messages %}{% if messages %}
        {% for message in messages %}
            <div class="toast toast-alert align-items-center text-bg-{{ message.tags }} border-0"
                 role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="5000">
                <div class="d-flex">
                    <div class="toast-body">{{ message }}</div>
                    <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
            </div>
        {% endfor %}
    {% endif %}{% endblock %}
</div>

{% block js %}
    <script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'font-awesome/js/all.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'clipboardjs/clipboard.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>
    {% if request.user.is_authenticated %}
        <script type="text/javascript" src="{% static 'main/js/user.js' %}"></script>
    {% endif %}
    {% if request.user.is_superuser %}
        <script type="text/javascript" src="{% static 'main/js/admin.js' %}"></script>
    {% endif %}
{% endblock %}

{% block tail %}{% endblock %}

</body>
</html>

app/templates/profile.html
{% extends "main.html" %}
{% load static %}
{% load home_tags %}
{% load cache %}
{% block test_active %}active{% endblock %}
{% block title %}Profile{% endblock %}

{% block head %}{% endblock %}

{% block body %}
{% cache 86400 profile_body request.user %}

    <h1>User Profile</h1>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Key</th>
          <th scope="col">Value</th>
          <th scope="col">Description</th>
        </tr>
      </thead>
      <tbody>
      <tr>
        <th scope="row">id</th>
        <td>{{ request.user.id }}</td>
        <td>Internal User ID</td>
      </tr>
      <tr>
        <th scope="row">username</th>
          <td>{{ request.user.username }}</td>
          <td>Discord User ID</td>
      </tr>
      <tr>
        <th scope="row">fist_name</th>
          <td>{{ request.user.fist_name }}</td>
          <td>Discord Username</td>
      </tr>
      <tr>
        <th scope="row">last_name</th>
          <td>{{ request.user.last_name }}</td>
          <td>Discord Discriminator</td>
      </tr>
      </tbody>
    </table>

    <pre><code>{{ data }}</code></pre>

{% endcache %}

{% endblock %}

{% block tail %}{% endblock %}

app/templates/speedtest.html
{% extends "main.html" %}
{% load static %}
{% load home_tags %}
{% load cache %}
{% block test_active %}active{% endblock %}
{% block title %}Test{% endblock %}

{% block head %}{% endblock %}

{% block body %}

    <h2>Speed Test</h2>

{#    <script type="text/javascript" src="{% static 'js/iframeResizer.min.js' %}"></script>#}

    <iframe class="w-100" id="speedtest_iframe" style="min-height: 520px;"
            src="{% get_config 'SPEEDTEST_URL' %}"
            allowTransparency="true" allowfullscreen>
    </iframe>

{#    <script>#}
{#        iFrameResize({ log: true }, '#speedtest_iframe')#}
{#    </script>#}

{% endblock %}

{% block tail %}
{#    <script type="text/javascript">#}
{#        $('html').addClass('h-100');#}
{#        $('body').addClass('h-100');#}
{#        $('.container-fluid').addClass('h-100');#}
{#    </script>#}
{% endblock %}